//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApplication.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreApplication.Infrastructure.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator.
        /// </summary>
        internal static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin credentials are not valid..
        /// </summary>
        internal static string ADMIN_CREDENTIAL_NOT_VALID {
            get {
                return ResourceManager.GetString("ADMIN_CREDENTIAL_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string CLAIM_ID {
            get {
                return ResourceManager.GetString("CLAIM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid credentials..
        /// </summary>
        internal static string CREDENTIALS_FAILED {
            get {
                return ResourceManager.GetString("CREDENTIALS_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving changes:.
        /// </summary>
        internal static string ERROR_SAVING_CHANGES {
            get {
                return ResourceManager.GetString("ERROR_SAVING_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal Server Error:.
        /// </summary>
        internal static string INTERNAL_SERVER_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JwtConfig:TokenExpirationInHours.
        /// </summary>
        internal static string JWT_TOKEN_EXPIRATION {
            get {
                return ResourceManager.GetString("JWT_TOKEN_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No products found.
        /// </summary>
        internal static string NO_PRODUCTS_FOUND {
            get {
                return ResourceManager.GetString("NO_PRODUCTS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order created successfully.
        /// </summary>
        internal static string ORDER_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The page and page size parameters must be greater than 0..
        /// </summary>
        internal static string PARAMS_PAGE_GREATER_ZERO {
            get {
                return ResourceManager.GetString("PARAMS_PAGE_GREATER_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product created successfully.
        /// </summary>
        internal static string PRODUCT_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("PRODUCT_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
    }
}
